export const ROLES = {
  APPLICATION_MANAGER: 'APPLICATION_MANAGER',
  BUSINESS_USER: 'BUSINESS_USER',
  CUSTOMER: 'CUSTOMER',
};

export const BUSINESS_PERMISSIONS = {
  QUEUE_MANAGE: 'QUEUE_MANAGE',
  SERVICE_MANAGE: 'SERVICE_MANAGE',
  ANALYTICS_VIEW: 'ANALYTICS_VIEW',
  SUBSCRIPTION_MANAGE: 'SUBSCRIPTION_MANAGE',
};

export const QUEUE_ENTRY_STATUS = {
  WAITING: 'WAITING',
  NOTIFIED: 'NOTIFIED',
  CALLED: 'CALLED',
  CHECKED_IN: 'CHECKED_IN',
  SERVING: 'SERVING',
  SERVED: 'SERVED',
  CANCELLED: 'CANCELLED',
  SKIPPED: 'SKIPPED',
  NO_SHOW: 'NO_SHOW',
};

export const QUEUE_STATUS = {
  OPEN: 'OPEN',
  PAUSED: 'PAUSED',
  CLOSED: 'CLOSED',
};
